### ISSUE TITLE
Database doesn't provision after the creation of DB Home

### ISSUE THREAD

**Issue by NarvekarS** [oracle-quickstart/oci-arch-db-migration#10]
Error: Invalid index
  on database.tf line 41, in resource "oci_database_database" "exacs_starter_database" 
  41:   db_home_id = data.oci_database_db_homes.exacs_db_homes.db_homes[0].id
    ├────────────────
    │ data.oci_database_db_homes.exacs_db_homes.db_homes is empty list of object
The given key does not identify an element in this collection value.
Error: Invalid index
  on datasources.tf line 76, in data "oci_database_databases" "exacs_databases" 
  76:   db_home_id     = data.oci_database_db_homes.exacs_db_homes.db_homes[0].id
    ├────────────────
    │ data.oci_database_db_homes.exacs_db_homes.db_homes is empty list of object
The given key does not identify an element in this collection value.

**Comment by NarvekarS** [comment]
I downloaded the ORM config, changed the dbhome[0] id to dbhome[1].id and uploaded the config back. Terraform plan failed.
I then changed it back to dbhome[0].id and uploaded it again.
This time terraform plan worked and apply is also running right now - starter db creation is in progress

**Comment by lfeldman** [comment]
Looks like data source `oci_database_db_homes.exacs_db_homes.db_homes[0].id` has been used before `oci_database_cloud_vm_cluster.exacs_vm_cluster `resource was finshed... That is why ulitmately after some time you were able to use it ... I was thinking about making direct dependency like this:

```
data "oci_database_db_homes" "exacs_db_homes" {
  depends_on = [oci_database_cloud_vm_cluster.exacs_vm_cluster]
  compartment_id = var.compartment_ocid
  vm_cluster_id  = oci_database_cloud_vm_cluster.exacs_vm_cluster.id
}
```

**Comment by lfeldman** [comment]
@NarvekarS could you please retest it with the latest release: https://github.com/oracle-quickstart/oci-arch-db-migration/releases/tag/v1.3
