### ISSUE TITLE
Invalid Parameter(s) when deploying ExaCS Quarter 2.92

### ISSUE THREAD

**Issue by lmfarley10** [oracle-quickstart/oci-arch-db-migration#14]
Getting the following error when trying to provision default Exadata quarter 2.92 shape - 

Error: 400-InvalidParameter
Provider version: 4.56.0, released on 2021-12-08.
Service: Database Cloud Exadata Infrastructure
Error Message: Provisioning of Exadata Cloud Service infrastructure failed. Configuration of compute and storage is supported for X8M launch only.
OPC request ID: bcebcc8646918cb093ac13b6caaeb6ce/90406DADF48D1521FB39D633CB3CF9BF/5C2D9B5BC3F6302769118CCD327C4CE0
Suggestion: Please Update the parameter(s) in the Terraform config as per error message Provisioning of Exadata Cloud Service infrastructure failed. Configuration of compute and storage is supported for X8M launch only.

Compute and Storage parameters currently default to 2 and 3 respectively.

**Comment by lfeldman** [comment]
@lmfarley10 the error you have received shows you are not using X8M with scaling options for compute & storage nodes. That is why you should change the variable in variables.tf as follows:
```
variable "exacs_x8_infra" {
  default = false
}
```
