### ISSUE TITLE
No DRG is created when using oci-arch-db-migration

### ISSUE THREAD

**Issue by mushtaqahmedmohammed** [oracle-quickstart/oci-arch-db-migration#19]
There is no DRG created in VCN but README.md shows DRG should have created. Any inputs why its not created. below is picture shown in our tenenancy where I created ExaCS infrastructure...

![image](https://user-images.githubusercontent.com/83082336/147288694-6ce4e7b7-0f4f-41ee-8709-85adbdafd74c.png)
![image](https://user-images.githubusercontent.com/83082336/147288706-6daeffcc-58b2-45aa-b0c1-91b73175e083.png)

**Comment by lfeldman** [comment]
@mushtaqahmedmohammed I have added DRG support.
