### ISSUE TITLE
ORM build fails for OCI Region with only one AD

### ISSUE THREAD

**Issue by aszynkow** [oracle-quickstart/oci-arch-db-migration#2]
Some OCI Regions (Sydney and Melbourne) have only one AD. Current version of the code is likely to fail in such OCI Regions.  (I have only tested the ExaCS scenario but seems reading all the ADs works same across all the scenarios)

The code should also cater for the "less than 3 ADs" scenario, please.

For now I used below as a workaround:

 data oci_identity_availability_domain AD1 {
  compartment_id = var.tenancy_ocid
  ad_number = "1"
}
and then:

availability_domain = data.oci_identity_availability_domain.AD1.name

Happy coding!!!

Regards,
Adam

**Comment by lfeldman** [comment]
@aszynkow with release: https://github.com/oracle-quickstart/oci-arch-db-migration/releases/tag/v1.2.1 we have added optional `availability_domain_name` variable or alternatively `availability_domain_number` variable. Closing issue.
