### ISSUE TITLE
Exadata DB API Deprecated

### ISSUE THREAD

**Issue by lmfarley10** [oracle-quickstart/oci-arch-db-migration#5]
When deploying the module ExaCS via terraform it throws the error -

`Creating a DB system resource is not supported for Exadata Cloud Service instances. Create a cloud Exadata infrastructure resource instead.`

I also noticed here the ExaCS DB API has been deprecated since May 15th -  
https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/exaflexsystem_topic-resource_model_conversion.htm

OCI Documentation on switching to new resource model apis - 
https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/exaflexsystem_topic-resource_model_conversion.htm#exaflexsystem_topic-to_switch_resource_model

API for Exadata Infrastructure - 
https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudExadataInfrastructure/CreateCloudExadataInfrastructure/

API for Cloud VM Cluster - 
https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudVmCluster/CreateCloudVmCluster/

**Comment by lfeldman** [comment]
@lmfarley10 we have updated the codes recently. Now testing it finally with ORM/RMS, but today you can try the code.

**Comment by lfeldman** [comment]
Final version is visible in this GitHub release: https://github.com/oracle-quickstart/oci-arch-db-migration/releases/tag/v1.2
